# File: .streamlit/config.toml



#[server]

#headless = true

#port = 8510

#enableCORS = false



[theme]

base = "light"

primaryColor = "#4CAF50"

backgroundColor = "#FFFFFF"

secondaryBackgroundColor = "#F0F2F6"

textColor = "#262730"

font = "sans serif"



#[theme]

#base = "dark"  # Change to "light" for light mode

#primaryColor = "#4CAF50"

#backgroundColor = "#0E1117"

#secondaryBackgroundColor = "#262730"

#textColor = "#FAFAFA"

#font = "sans serif"



#[client]

#showSidebarNavigation = true

#toolbarMode = "minimal"